/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import javax.swing.JOptionPane;
import javax.swing.UIManager;
import rojerusan.RSAnimation;

/**
 *
 * @author Guffy
 */
public class VentanaConsultar extends javax.swing.JFrame {

    /**
     * Creates new form VentanaConsultar
     */
    int xMouse;
    int yMouse;
    public VentanaConsultar() {
        initComponents();
        this.setLocationRelativeTo(null);
        RSAnimation.setBajar(-50, 200, 2, 2, this);
        try{
            
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
            
        }
        catch (Exception e){
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenedor = new javax.swing.JPanel();
        btnProductosOrdenadosAZ = new javax.swing.JButton();
        btnProductosMasVendidos = new javax.swing.JButton();
        btnClientesProductosFrescos = new javax.swing.JButton();
        btnEliminarProducto1 = new javax.swing.JButton();
        btnEliminarProducto2 = new javax.swing.JButton();
        btnEliminarProducto3 = new javax.swing.JButton();
        jPanelRound1 = new LIB.JPanelRound();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        LabelAñadirNuevoProducto = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        contenedor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnProductosOrdenadosAZ.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/MostrarProductosAZ.png"))); // NOI18N
        btnProductosOrdenadosAZ.setBorderPainted(false);
        btnProductosOrdenadosAZ.setContentAreaFilled(false);
        btnProductosOrdenadosAZ.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/MostrarProductosAZOVER.png"))); // NOI18N
        btnProductosOrdenadosAZ.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnProductosOrdenadosAZMouseMoved(evt);
            }
        });
        btnProductosOrdenadosAZ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductosOrdenadosAZActionPerformed(evt);
            }
        });
        contenedor.add(btnProductosOrdenadosAZ, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 170, 200, 50));

        btnProductosMasVendidos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ProductosMasVendidos.png"))); // NOI18N
        btnProductosMasVendidos.setBorderPainted(false);
        btnProductosMasVendidos.setContentAreaFilled(false);
        btnProductosMasVendidos.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ProductosMasVendidosOVER.png"))); // NOI18N
        btnProductosMasVendidos.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnProductosMasVendidosMouseMoved(evt);
            }
        });
        btnProductosMasVendidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductosMasVendidosActionPerformed(evt);
            }
        });
        contenedor.add(btnProductosMasVendidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(446, 220, 200, 50));

        btnClientesProductosFrescos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ClientesProductosFrescos.png"))); // NOI18N
        btnClientesProductosFrescos.setBorderPainted(false);
        btnClientesProductosFrescos.setContentAreaFilled(false);
        btnClientesProductosFrescos.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ClientesProductosFrescosOVER.png"))); // NOI18N
        btnClientesProductosFrescos.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnClientesProductosFrescosMouseMoved(evt);
            }
        });
        btnClientesProductosFrescos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesProductosFrescosActionPerformed(evt);
            }
        });
        contenedor.add(btnClientesProductosFrescos, new org.netbeans.lib.awtextra.AbsoluteConstraints(669, 170, 200, 50));

        btnEliminarProducto1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/TiempoPromedio.png"))); // NOI18N
        btnEliminarProducto1.setBorderPainted(false);
        btnEliminarProducto1.setContentAreaFilled(false);
        btnEliminarProducto1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/TiempoPromedioOVER.png"))); // NOI18N
        btnEliminarProducto1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnEliminarProducto1MouseMoved(evt);
            }
        });
        btnEliminarProducto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarProducto1ActionPerformed(evt);
            }
        });
        contenedor.add(btnEliminarProducto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 380, 200, 50));

        btnEliminarProducto2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/TopClientesCompradores.png"))); // NOI18N
        btnEliminarProducto2.setBorderPainted(false);
        btnEliminarProducto2.setContentAreaFilled(false);
        btnEliminarProducto2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/TopClientesCompradoresOVER.png"))); // NOI18N
        btnEliminarProducto2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnEliminarProducto2MouseMoved(evt);
            }
        });
        btnEliminarProducto2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarProducto2ActionPerformed(evt);
            }
        });
        contenedor.add(btnEliminarProducto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(446, 330, 200, 50));

        btnEliminarProducto3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/montosaltosbajos.png"))); // NOI18N
        btnEliminarProducto3.setBorderPainted(false);
        btnEliminarProducto3.setContentAreaFilled(false);
        btnEliminarProducto3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/montosaltosbajosOVER.png"))); // NOI18N
        btnEliminarProducto3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnEliminarProducto3MouseMoved(evt);
            }
        });
        btnEliminarProducto3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarProducto3ActionPerformed(evt);
            }
        });
        contenedor.add(btnEliminarProducto3, new org.netbeans.lib.awtextra.AbsoluteConstraints(669, 380, 200, 50));

        jPanelRound1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanelRound1MouseDragged(evt);
            }
        });
        jPanelRound1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelRound1MousePressed(evt);
            }
        });

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/back_arrow_35px.png"))); // NOI18N
        jButton6.setBorder(null);
        jButton6.setBorderPainted(false);
        jButton6.setContentAreaFilled(false);
        jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton6.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/shutdown35px.png"))); // NOI18N
        jButton7.setBorder(null);
        jButton7.setBorderPainted(false);
        jButton7.setContentAreaFilled(false);
        jButton7.setFocusPainted(false);
        jButton7.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        LabelAñadirNuevoProducto.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        LabelAñadirNuevoProducto.setForeground(new java.awt.Color(255, 255, 255));
        LabelAñadirNuevoProducto.setText("Consultar");

        javax.swing.GroupLayout jPanelRound1Layout = new javax.swing.GroupLayout(jPanelRound1);
        jPanelRound1.setLayout(jPanelRound1Layout);
        jPanelRound1Layout.setHorizontalGroup(
            jPanelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRound1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(462, 462, 462)
                .addComponent(LabelAñadirNuevoProducto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 477, Short.MAX_VALUE)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );
        jPanelRound1Layout.setVerticalGroup(
            jPanelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRound1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelAñadirNuevoProducto)
                    .addComponent(jButton7)
                    .addComponent(jButton6))
                .addContainerGap())
        );

        contenedor.add(jPanelRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1160, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/imagenFondo.png"))); // NOI18N
        contenedor.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 1120, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(contenedor, javax.swing.GroupLayout.PREFERRED_SIZE, 1117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(contenedor, javax.swing.GroupLayout.PREFERRED_SIZE, 635, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        VentanaPrincipal nuevo = new VentanaPrincipal();
        nuevo.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jPanelRound1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelRound1MouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_jPanelRound1MouseDragged

    private void jPanelRound1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelRound1MousePressed
        // TODO add your handling code here:
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jPanelRound1MousePressed

    private void btnClientesProductosFrescosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesProductosFrescosActionPerformed
        // TODO add your handling code here:
   JOptionPane.showMessageDialog(null, "En Construccion");

    }//GEN-LAST:event_btnClientesProductosFrescosActionPerformed

    private void btnClientesProductosFrescosMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClientesProductosFrescosMouseMoved
        // TODO add your handling code here:
       
    }//GEN-LAST:event_btnClientesProductosFrescosMouseMoved

    private void btnProductosMasVendidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductosMasVendidosActionPerformed
        // TODO add your handling code here:
     JOptionPane.showMessageDialog(null, "En Construccion");
    }//GEN-LAST:event_btnProductosMasVendidosActionPerformed

    private void btnProductosMasVendidosMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProductosMasVendidosMouseMoved
        // TODO add your handling code here:
     
    }//GEN-LAST:event_btnProductosMasVendidosMouseMoved

    private void btnProductosOrdenadosAZActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductosOrdenadosAZActionPerformed
        // TODO add your handling code here:
        VentanaProductosAZ p = new VentanaProductosAZ();
        p.setVisible(true);
        this.setVisible(false);
        this.dispose();
      
    }//GEN-LAST:event_btnProductosOrdenadosAZActionPerformed

    private void btnProductosOrdenadosAZMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProductosOrdenadosAZMouseMoved
        // TODO add your handling code here:
       
    }//GEN-LAST:event_btnProductosOrdenadosAZMouseMoved

    private void btnEliminarProducto1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarProducto1MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarProducto1MouseMoved

    private void btnEliminarProducto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarProducto1ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "En Construccion");
    }//GEN-LAST:event_btnEliminarProducto1ActionPerformed

    private void btnEliminarProducto2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarProducto2MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarProducto2MouseMoved

    private void btnEliminarProducto2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarProducto2ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "En Construccion");
    }//GEN-LAST:event_btnEliminarProducto2ActionPerformed

    private void btnEliminarProducto3MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarProducto3MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarProducto3MouseMoved

    private void btnEliminarProducto3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarProducto3ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "En Construccion");
    }//GEN-LAST:event_btnEliminarProducto3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaConsultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaConsultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaConsultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaConsultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaConsultar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelAñadirNuevoProducto;
    private javax.swing.JButton btnClientesProductosFrescos;
    private javax.swing.JButton btnEliminarProducto1;
    private javax.swing.JButton btnEliminarProducto2;
    private javax.swing.JButton btnEliminarProducto3;
    private javax.swing.JButton btnProductosMasVendidos;
    private javax.swing.JButton btnProductosOrdenadosAZ;
    private javax.swing.JPanel contenedor;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private LIB.JPanelRound jPanelRound1;
    // End of variables declaration//GEN-END:variables
}
